language: node_js
node_js:
  - "6"
  
cache:
  bundler: true
  directories:
    - "node_modules"

before_install:
  - gem install deb-s3
  - openssl aes-256-cbc -K $encrypted_ace8744cfeee_key -iv $encrypted_ace8744cfeee_iv -in codesigning.asc.enc -out codesigning.asc -d

script:
  - npm run build
  - npm test
  - sh build-debian.sh
