language: node_js
node_js:
  - "15"
  
cache:
  bundler: true
  directories:
    - "node_modules"

before_install:
  - gem install deb-s3 -v 0.10.0 

script:
  - set -e
  - npm run build
  - npm test
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then sh build-debian.sh; fi
