language: node_js
node_js:
  - "6"
  
cache:
  bundler: true
  directories:
    - "node_modules"

before_install:
  - gem install deb-s3

script:
  - npm run build
  - npm test
  - sh build-debian.sh
