on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Use Node.js 15.x
      uses: actions/setup-node@v3
      with:
        node-version: '15.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - run: npm run build
    - run: npm test
    - name: Import GPG key
      if: github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    - name: Configure AWS Credentials
      if: github.ref == 'refs/heads/master'
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        set -e
        DATE=$(date '+%Y%m%d%H%M%S')
        echo "Version: ${DATE}" >> debian/DEBIAN/control
        dpkg-deb --build debian r2cloud-ui-${DATE}.deb
        mkdir -p ~/.m2/repository/
        [[ -f ~/.m2/repository/apt-cli-1.6.jar ]] || wget --no-clobber --quiet -O ~/.m2/repository/apt-cli-1.6.jar https://github.com/dernasherbrezon/apt-cli/releases/download/apt-cli-1.6/apt-cli.jar
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename r2cloud --gpg-keyname F2DCBFDCA5A70917  save --patterns ./*.deb
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename stretch --gpg-keyname F2DCBFDCA5A70917  save --patterns ./*.deb
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename buster --gpg-keyname F2DCBFDCA5A70917  save --patterns ./*.deb
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename bullseye --gpg-keyname F2DCBFDCA5A70917  save --patterns ./*.deb
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename bookworm --gpg-keyname F2DCBFDCA5A70917  save --patterns ./*.deb
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename bionic --gpg-keyname F2DCBFDCA5A70917  save --patterns ./*.deb
        java -jar ~/.m2/repository/apt-cli-1.6.jar --url s3://r2cloud --component main --codename focal --gpg-keyname F2DCBFDCA5A70917   save --patterns ./*.deb
